### PR TITLE
Use /usr/local instead of /usr, don't assume everything is in /bin

### PR DESCRIPTION
**Pull request by Steffan153**
On macOS when trying to install in /usr, it will just throw "Operation not permitted" because it's protected by system. Things should go in `/usr/local` instead.

It's likely things won't be in `/bin`, it could be anything in the path, for example on Mac things might be in `/opt/homebrew/bin`, so I changed it to just look for the langs anywhere in the path.

### CODE REVIEW

**Comment by aderepas** [comment]
Thank you for your contribution!
Didn't think about that.
But there are some problems.

First, Linux systems don't use /usr/local/bin, but /usr/bin.
Second, the PKGBUILD shouldn't be changed because of MacOS.
The PKGBUILD is to build the package for the AUR, and therefore, it's not for MacOS.

And I just realised that I didn't pushed the latest changed to the repo, so there is now a conflict with the src/PKGBUILD

**Comment by aderepas** [comment]
@Steffan153 Can't you just `sudo make install` ?

**Comment by Steffan153** [comment]
No, it won't even work with `sudo`. Mac protects the folder completely.

**Comment by Steffan153** [comment]
I don't think your "Check for executable files if they are not in the PATH" commit is necessary because `/usr/bin` and `/bin` will almost always be in the path.

**Comment by Steffan153** [comment]
I'm pretty sure most any linux distro will have `/usr/local/bin` in the path. https://unix.stackexchange.com/questions/4186/what-is-usr-local-bin

**Comment by aderepas** [comment]
> No, it won't even work with sudo. Mac protects the folder completely.
My bad!

You were actually right!
`/usr/local/bin` should be used when installing langfetch with make.
But when installing with a PKG manager, it should be in `/usr/bin`.
Source: https://unix.stackexchange.com/questions/8656/usr-bin-vs-usr-local-bin-on-linux

Even tho it will be more convenient to just write `python` instead of `/usr/bin/python`.
It would be too risky to assume that the OS necessarily has that in the PATH.

**Pull request closed without merging**
